# Generated by Django 4.2.4 on 2023-08-24 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izoh',
            name='kino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kino.kino'),
        ),
    ]
